version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
      - otel-collector
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && exec airflow webserver"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg

  scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
      - otel-collector
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    volumes:
      - victoriametrics_data:/victoria-metrics-data

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - victoriametrics
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  victoriametrics_data:
  grafana_data:
